language: go
go:
  - 1.7
  - 1.8

sudo: required

services:
  - cassandra

before_script:
  # peg
  - go get -u github.com/pointlander/peg
  - go get -u golang.org/x/tools/cmd/goimports
  - cqlsh -f metric_metadata/cassandra/schema/schema_test.cql

script:
  - ./testing_support/script/verify-build
  - go test -v -timeout 1m ./...
